eureka:
  client:
    service-url:
      defaultZone: http://192.168.191.1:8081/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
server:
  port: 8082
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://192.168.191.1:8080
  cloud:
    client.ipAddress: 192.168.191.1