package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbFacebookSysTask;
import com.shty.collect.domain.TbFacebookSysTaskgroup;
import com.shty.collect.web.rest.dto.Syste_Facebook_Task_Attribute_Group;
import com.shty.collect.web.rest.dto.System_GroupAnd_AttributeDto;
import com.shty.collect.web.rest.dto.Task_StatusDto;

public interface TbFacebookSysTaskgroupMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteGroup(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int addGroup(TbFacebookSysTaskgroup group);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbFacebookSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbFacebookSysTaskgroup selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateGroup(TbFacebookSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskgroup
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbFacebookSysTaskgroup record);
	
	public List<System_GroupAnd_AttributeDto> getTaskgroupAll(String groupType);
	
	public List<System_GroupAnd_AttributeDto> getTaskgroupAll1();
	
	public List<System_GroupAnd_AttributeDto> getTaskgroupKeyWord();
	
	public List<Syste_Facebook_Task_Attribute_Group> getByidGroup(Long id);
	
	public List<Syste_Facebook_Task_Attribute_Group> getGroupByid(Long id);
	
	public List<Syste_Facebook_Task_Attribute_Group> select_Task(String task_static) ;
	
	public int updateGroup_task_static(Task_StatusDto statusDto);
	
	public int updateGroupStatus(Task_StatusDto task_statusdto);
}