package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbFacebookSysTaskattribute;

public interface TbFacebookSysTaskattributeMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteAttribute(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbFacebookSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbFacebookSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbFacebookSysTaskattribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateAttribute(TbFacebookSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbFacebookSysTaskattribute record);
	
	public List<TbFacebookSysTaskattribute> getAllattribute();
	
	public void addAttribute(TbFacebookSysTaskattribute TbFacebookSysTaskattribute);
	
}