package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbFacebookSysTask;
import com.shty.collect.domain.TbTwitterCount;

public interface TbFacebookSysTaskMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteTask(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int addTask(TbFacebookSysTask record);
	
	
	int addthirdTask(TbFacebookSysTask tbFacebookSysTask);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbFacebookSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbFacebookSysTask selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbFacebookSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_facebook_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateTask(TbFacebookSysTask record);
	
	TbFacebookSysTask select_Task();
	
	int MonitoringGroupTask(Long Groupid);
	
	int StopMonitoringGroupTask(Long Groupid);
	
	
	int MonitoringTask(Long id);
	
	int StopMonitoringTask(Long id);
	
	int update_task_taskStatus(Long id);
	
	public TbFacebookSysTask select_taskUrl(String url);
	
	public TbTwitterCount getFacebookCountValue(Integer number);
	
	public TbFacebookSysTask getFacebookTask(String taskStatus);
	
	public List<TbFacebookSysTask> getFacebookthrid(int third_id);
}