package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbLinkedinSysKeyword;
import com.shty.collect.web.rest.dto.LinkedinKeywordDto;

public interface TbLinkedinSysKeywordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	int insert(TbLinkedinSysKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	int insertSelective(TbLinkedinSysKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	TbLinkedinSysKeyword selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	int updateByPrimaryKeySelective(TbLinkedinSysKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_keyword
	 *
	 * @mbg.generated Tue Aug 15 09:10:10 CST 2017
	 */
	int updateByPrimaryKey(TbLinkedinSysKeyword record);

	List<LinkedinKeywordDto> getAllKeyword();

	List<LinkedinKeywordDto> getKeywordByGroupId(int id);

	TbLinkedinSysKeyword selectOneKeyword();

}