package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbLinkedinSysTaskgroup;
import com.shty.collect.web.rest.dto.LnkKeywordGroupDto;

public interface TbLinkedinSysTaskgroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbLinkedinSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbLinkedinSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	TbLinkedinSysTaskgroup selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbLinkedinSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbLinkedinSysTaskgroup record);

	List<LnkKeywordGroupDto> getAllKeywordGroup();
}