package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbLinkedinSysTask;
import com.shty.collect.web.rest.dto.LnkTaskDto;

public interface TbLinkedinSysTaskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	int insert(TbLinkedinSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	int insertSelective(TbLinkedinSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	TbLinkedinSysTask selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	int updateByPrimaryKeySelective(TbLinkedinSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_linkedin_sys_task
	 *
	 * @mbg.generated Tue Sep 05 15:56:09 CST 2017
	 */
	int updateByPrimaryKey(TbLinkedinSysTask record);

	TbLinkedinSysTask getOneTask();

	List<TbLinkedinSysTask> getAllTask();

	List<LnkTaskDto> getTaskById(int id);

	TbLinkedinSysTask getTaskByurlpattern(String urlpattern);
}