package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbSystemRelation;
import com.shty.collect.web.rest.dto.System_Node_Socialacount_LinkaccountDto;

public interface TbSystemRelationMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteReation(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert_Reation(TbSystemRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbSystemRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbSystemRelation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbSystemRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_relation
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int update_Reation(TbSystemRelation record);
	
	public  List<TbSystemRelation> select_Reation_nodeid(Long id);
	
	public List<TbSystemRelation> select_Reation_id(Long id);
	
	public List<System_Node_Socialacount_LinkaccountDto> select_ReationAll();
	
}