package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbSystemSocialaccount;
import com.shty.collect.web.rest.dto.System_socialAccountDto;

public interface TbSystemSocialaccountMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbSystemSocialaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbSystemSocialaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbSystemSocialaccount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbSystemSocialaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_socialaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbSystemSocialaccount record);
	
	/**
	 * 查询账号表的全部数据
	 * @return
	 */
	public List<System_socialAccountDto> getAllaccount();
	
	/**
	 * 添加账号表数据
	 * @return
	 */
	public Integer addAccount(TbSystemSocialaccount tbSystemSocialaccount);
	
	/**
	 * 修改账号表数据
	 * @return
	 */
	public Integer updateAccount(TbSystemSocialaccount tbSystemSocialaccount);
	
	public Integer deletesocialAccount(Long id);
	
	public TbSystemSocialaccount select_socialAcount_id(Long id);
	
	public List<System_socialAccountDto> getAllaccountIsuesdTo();
	
	public List<System_socialAccountDto> getAllaccountIsuesd(Long id);
	
	public TbSystemSocialaccount select_type_facebook(String accountType);
	
	public List<TbSystemSocialaccount> getAllAccountName();
}