package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbSystemLinkaccount;

public interface TbSystemLinkaccountMapper  {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbSystemLinkaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbSystemLinkaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbSystemLinkaccount selectByPrimaryKey(Long id);

	/**
	 * this method was by generated liu.
	 * 20170607*/
	List<TbSystemLinkaccount> selectAll();
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbSystemLinkaccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_linkaccount
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbSystemLinkaccount record);
	
	/**
	 * 查询VPN全部数据
	 * @return
	 */
	public List<TbSystemLinkaccount> getAllLinkaccount();
}