package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbSystemSociallimit;

public interface TbSystemSociallimitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbSystemSociallimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbSystemSociallimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbSystemSociallimit selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbSystemSociallimit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_sociallimit
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbSystemSociallimit record);
	
	//查询限制表中的全部数据
	public List<TbSystemSociallimit> getAllLimit();
}