package com.shty.collect.dao;

import com.shty.collect.domain.TbSystemRecord;

public interface TbSystemRecordMapper  {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbSystemRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbSystemRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbSystemRecord selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbSystemRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_system_record
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbSystemRecord record);
}