package com.shty.collect.dao;

import com.shty.collect.domain.TbTwitterSysTask;

public interface TbTwitterSysTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbTwitterSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbTwitterSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbTwitterSysTask selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbTwitterSysTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_task
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbTwitterSysTask record);
	
	TbTwitterSysTask getTwitterTask();
    int addTwitterTask(TbTwitterSysTask record);
    int updateTwitterTask(TbTwitterSysTask record);
    int deteleTwitterTask(Long id);
    
	int monitoringTwitterGroupTask(Long taskgroupid);	
	int stopMonitoringTwitterGroupTask(Long taskgroupid);		
	int monitoringTwitterTask(Long id);
	int stopMonitoringTwitterTask(Long id);
	int updateTwitterTaskStatusStatic(TbTwitterSysTask record);
}