package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbTwitterSysTaskattribute;

public interface TbTwitterSysTaskattributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbTwitterSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbTwitterSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	TbTwitterSysTaskattribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbTwitterSysTaskattribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_twitter_sys_taskattribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbTwitterSysTaskattribute record);
	public List<TbTwitterSysTaskattribute> getTwitterAllAttribute();
	public void addTwitterAllAttribute(TbTwitterSysTaskattribute  tbTwitterSysTaskattribute);
	public void updateTwitterAllAttribute(TbTwitterSysTaskattribute tbTwitterSysTaskattribute);
	int deleteTwitterAllAttribute(Long id);
}