package com.shty.collect.dao;

import java.util.List;

import com.shty.collect.domain.TbTwitterSysTaskgroup;
import com.shty.collect.web.rest.dto.System_Twitter_TaskGroupAttrDto;
import com.shty.collect.web.rest.dto.System_Twitter_TaskGroupDto;

public interface TbTwitterSysTaskgroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int insert(TbTwitterSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int insertSelective(TbTwitterSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	TbTwitterSysTaskgroup selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TbTwitterSysTaskgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_twitter_sys_taskgroup
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	int updateByPrimaryKey(TbTwitterSysTaskgroup record);
	public List<System_Twitter_TaskGroupDto> getAllGroupAttribute();
	public List<System_Twitter_TaskGroupDto> getAllGroupAttributeSearch();
	public List<TbTwitterSysTaskgroup> getGroupSearchKeyWord(Long id);
	int addGroupAttribute(TbTwitterSysTaskgroup record);
	int updateGroupAttribute(TbTwitterSysTaskgroup record);
	int deleteGroupAttribute(Long id);
	public List<System_Twitter_TaskGroupAttrDto>getGroupDetailByid(Long id);
	public List<System_Twitter_TaskGroupAttrDto>selectTwitterTaskUrl(String taskStatus);
}