package com.shty.collect.domain;

import java.util.Date;

public class TbFacebookSysTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.URL
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	
	private String taskName;
	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.taskAttributeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long taskattributeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.taskStatus
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String taskstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.priority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.taskGroupId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long taskgroupid;
	
	private int third_id;
	
	
	private long FBTarget_id;
	 
	public long getFBTarget_id() {
		return FBTarget_id;
	}

	public void setFBTarget_id(long fBTarget_id) {
		FBTarget_id = fBTarget_id;
	}

	public int getThird_id() {
		return third_id;
	}

	public void setThird_id(int third_id) {
		this.third_id = third_id;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_task.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.id
	 * @return  the value of tb_facebook_sys_task.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.id
	 * @param id  the value for tb_facebook_sys_task.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.URL
	 * @return  the value of tb_facebook_sys_task.URL
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.URL
	 * @param url  the value for tb_facebook_sys_task.URL
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.taskAttributeId
	 * @return  the value of tb_facebook_sys_task.taskAttributeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getTaskattributeid() {
		return taskattributeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.taskAttributeId
	 * @param taskattributeid  the value for tb_facebook_sys_task.taskAttributeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setTaskattributeid(Long taskattributeid) {
		this.taskattributeid = taskattributeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.taskStatus
	 * @return  the value of tb_facebook_sys_task.taskStatus
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getTaskstatus() {
		return taskstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.taskStatus
	 * @param taskstatus  the value for tb_facebook_sys_task.taskStatus
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setTaskstatus(String taskstatus) {
		this.taskstatus = taskstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.priority
	 * @return  the value of tb_facebook_sys_task.priority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.priority
	 * @param priority  the value for tb_facebook_sys_task.priority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setPriority(String priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.taskGroupId
	 * @return  the value of tb_facebook_sys_task.taskGroupId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getTaskgroupid() {
		return taskgroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.taskGroupId
	 * @param taskgroupid  the value for tb_facebook_sys_task.taskGroupId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setTaskgroupid(Long taskgroupid) {
		this.taskgroupid = taskgroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.creatTime
	 * @return  the value of tb_facebook_sys_task.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.creatTime
	 * @param creattime  the value for tb_facebook_sys_task.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_task.updateTime
	 * @return  the value of tb_facebook_sys_task.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_task.updateTime
	 * @param updatetime  the value for tb_facebook_sys_task.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}