package com.shty.collect.domain;

import java.util.Date;

public class TbFacebookSysTaskattribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.weekChoice
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String weekchoice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.startRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String startregiontime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.endRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String endregiontime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.endTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String startTime;
	
	private String endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.downLoadAttribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String downloadattribute;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_facebook_sys_taskattribute.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.id
	 * @return  the value of tb_facebook_sys_taskattribute.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.id
	 * @param id  the value for tb_facebook_sys_taskattribute.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.weekChoice
	 * @return  the value of tb_facebook_sys_taskattribute.weekChoice
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getWeekchoice() {
		return weekchoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.weekChoice
	 * @param weekchoice  the value for tb_facebook_sys_taskattribute.weekChoice
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setWeekchoice(String weekchoice) {
		this.weekchoice = weekchoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.startRegionTime
	 * @return  the value of tb_facebook_sys_taskattribute.startRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getStartregiontime() {
		return startregiontime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.startRegionTime
	 * @param startregiontime  the value for tb_facebook_sys_taskattribute.startRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setStartregiontime(String startregiontime) {
		this.startregiontime = startregiontime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.endRegionTime
	 * @return  the value of tb_facebook_sys_taskattribute.endRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getEndregiontime() {
		return endregiontime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.endRegionTime
	 * @param endregiontime  the value for tb_facebook_sys_taskattribute.endRegionTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setEndregiontime(String endregiontime) {
		this.endregiontime = endregiontime;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.endTime
	 * @return  the value of tb_facebook_sys_taskattribute.endTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.endTime
	 * @param endtime  the value for tb_facebook_sys_taskattribute.endTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.downLoadAttribute
	 * @return  the value of tb_facebook_sys_taskattribute.downLoadAttribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getDownloadattribute() {
		return downloadattribute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.downLoadAttribute
	 * @param downloadattribute  the value for tb_facebook_sys_taskattribute.downLoadAttribute
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setDownloadattribute(String downloadattribute) {
		this.downloadattribute = downloadattribute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.creatTime
	 * @return  the value of tb_facebook_sys_taskattribute.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.creatTime
	 * @param creattime  the value for tb_facebook_sys_taskattribute.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_facebook_sys_taskattribute.updateTime
	 * @return  the value of tb_facebook_sys_taskattribute.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_facebook_sys_taskattribute.updateTime
	 * @param updatetime  the value for tb_facebook_sys_taskattribute.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}