package com.shty.collect.domain;

import java.util.Date;

public class TbLinkedinSysTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.id
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.finished
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Integer finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.fullname
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.lnkid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String lnkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.URL
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.urlpattern
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String urlpattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.summary
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.headline
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String headline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.location
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.taskAttributeId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Long taskattributeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.taskStatus
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String taskstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.priority
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.keywordid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Integer keywordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.taskGroupId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Long taskgroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.creatTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_task.updateTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.id
     *
     * @return the value of tb_linkedin_sys_task.id
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.id
     *
     * @param id the value for tb_linkedin_sys_task.id
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.finished
     *
     * @return the value of tb_linkedin_sys_task.finished
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Integer getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.finished
     *
     * @param finished the value for tb_linkedin_sys_task.finished
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setFinished(Integer finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.fullname
     *
     * @return the value of tb_linkedin_sys_task.fullname
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.fullname
     *
     * @param fullname the value for tb_linkedin_sys_task.fullname
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.lnkid
     *
     * @return the value of tb_linkedin_sys_task.lnkid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getLnkid() {
        return lnkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.lnkid
     *
     * @param lnkid the value for tb_linkedin_sys_task.lnkid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setLnkid(String lnkid) {
        this.lnkid = lnkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.URL
     *
     * @return the value of tb_linkedin_sys_task.URL
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.URL
     *
     * @param url the value for tb_linkedin_sys_task.URL
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.urlpattern
     *
     * @return the value of tb_linkedin_sys_task.urlpattern
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getUrlpattern() {
        return urlpattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.urlpattern
     *
     * @param urlpattern the value for tb_linkedin_sys_task.urlpattern
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setUrlpattern(String urlpattern) {
        this.urlpattern = urlpattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.summary
     *
     * @return the value of tb_linkedin_sys_task.summary
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.summary
     *
     * @param summary the value for tb_linkedin_sys_task.summary
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.headline
     *
     * @return the value of tb_linkedin_sys_task.headline
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getHeadline() {
        return headline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.headline
     *
     * @param headline the value for tb_linkedin_sys_task.headline
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setHeadline(String headline) {
        this.headline = headline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.location
     *
     * @return the value of tb_linkedin_sys_task.location
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.location
     *
     * @param location the value for tb_linkedin_sys_task.location
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.taskAttributeId
     *
     * @return the value of tb_linkedin_sys_task.taskAttributeId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Long getTaskattributeid() {
        return taskattributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.taskAttributeId
     *
     * @param taskattributeid the value for tb_linkedin_sys_task.taskAttributeId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setTaskattributeid(Long taskattributeid) {
        this.taskattributeid = taskattributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.taskStatus
     *
     * @return the value of tb_linkedin_sys_task.taskStatus
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getTaskstatus() {
        return taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.taskStatus
     *
     * @param taskstatus the value for tb_linkedin_sys_task.taskStatus
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setTaskstatus(String taskstatus) {
        this.taskstatus = taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.priority
     *
     * @return the value of tb_linkedin_sys_task.priority
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.priority
     *
     * @param priority the value for tb_linkedin_sys_task.priority
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.keywordid
     *
     * @return the value of tb_linkedin_sys_task.keywordid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Integer getKeywordid() {
        return keywordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.keywordid
     *
     * @param keywordid the value for tb_linkedin_sys_task.keywordid
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setKeywordid(Integer keywordid) {
        this.keywordid = keywordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.taskGroupId
     *
     * @return the value of tb_linkedin_sys_task.taskGroupId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Long getTaskgroupid() {
        return taskgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.taskGroupId
     *
     * @param taskgroupid the value for tb_linkedin_sys_task.taskGroupId
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setTaskgroupid(Long taskgroupid) {
        this.taskgroupid = taskgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.creatTime
     *
     * @return the value of tb_linkedin_sys_task.creatTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.creatTime
     *
     * @param creattime the value for tb_linkedin_sys_task.creatTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_task.updateTime
     *
     * @return the value of tb_linkedin_sys_task.updateTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_task.updateTime
     *
     * @param updatetime the value for tb_linkedin_sys_task.updateTime
     *
     * @mbg.generated Tue Sep 05 15:56:09 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}