package com.shty.collect.domain;

import java.util.Date;

public class TbLinkedinSysKeyword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.id
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.finished
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private Integer finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.groupid
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.keyword
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.createtime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_linkedin_sys_keyword.updatatime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    private Date updatatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.id
     *
     * @return the value of tb_linkedin_sys_keyword.id
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.id
     *
     * @param id the value for tb_linkedin_sys_keyword.id
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.finished
     *
     * @return the value of tb_linkedin_sys_keyword.finished
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public Integer getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.finished
     *
     * @param finished the value for tb_linkedin_sys_keyword.finished
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setFinished(Integer finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.groupid
     *
     * @return the value of tb_linkedin_sys_keyword.groupid
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.groupid
     *
     * @param groupid the value for tb_linkedin_sys_keyword.groupid
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.keyword
     *
     * @return the value of tb_linkedin_sys_keyword.keyword
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.keyword
     *
     * @param keyword the value for tb_linkedin_sys_keyword.keyword
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.createtime
     *
     * @return the value of tb_linkedin_sys_keyword.createtime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.createtime
     *
     * @param createtime the value for tb_linkedin_sys_keyword.createtime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_linkedin_sys_keyword.updatatime
     *
     * @return the value of tb_linkedin_sys_keyword.updatatime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public Date getUpdatatime() {
        return updatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_linkedin_sys_keyword.updatatime
     *
     * @param updatatime the value for tb_linkedin_sys_keyword.updatatime
     *
     * @mbg.generated Tue Aug 15 09:10:10 CST 2017
     */
    public void setUpdatatime(Date updatatime) {
        this.updatatime = updatatime;
    }
}