package com.shty.collect.domain;

import java.util.Date;

public class TbLinkedinSysTaskgroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.id
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.groupName
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private String groupname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.groupStatus
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private String groupstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.groupType
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private String grouptype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.priority
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.keyWord
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.taskAttributeId
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private Long taskattributeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.creatTime
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_linkedin_sys_taskgroup.updateTime
	 * 
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.id
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.id
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.id
	 * 
	 * @param id
	 *            the value for tb_linkedin_sys_taskgroup.id
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.groupName
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.groupName
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public String getGroupname() {
		return groupname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.groupName
	 * 
	 * @param groupname
	 *            the value for tb_linkedin_sys_taskgroup.groupName
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.groupStatus
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.groupStatus
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public String getGroupstatus() {
		return groupstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.groupStatus
	 * 
	 * @param groupstatus
	 *            the value for tb_linkedin_sys_taskgroup.groupStatus
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setGroupstatus(String groupstatus) {
		this.groupstatus = groupstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.groupType
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.groupType
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public String getGrouptype() {
		return grouptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.groupType
	 * 
	 * @param grouptype
	 *            the value for tb_linkedin_sys_taskgroup.groupType
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setGrouptype(String grouptype) {
		this.grouptype = grouptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.priority
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.priority
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.priority
	 * 
	 * @param priority
	 *            the value for tb_linkedin_sys_taskgroup.priority
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.keyWord
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.keyWord
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.keyWord
	 * 
	 * @param keyword
	 *            the value for tb_linkedin_sys_taskgroup.keyWord
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.taskAttributeId
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.taskAttributeId
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getTaskattributeid() {
		return taskattributeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.taskAttributeId
	 * 
	 * @param taskattributeid
	 *            the value for tb_linkedin_sys_taskgroup.taskAttributeId
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setTaskattributeid(Long taskattributeid) {
		this.taskattributeid = taskattributeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.creatTime
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.creatTime
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.creatTime
	 * 
	 * @param creattime
	 *            the value for tb_linkedin_sys_taskgroup.creatTime
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_linkedin_sys_taskgroup.updateTime
	 * 
	 * @return the value of tb_linkedin_sys_taskgroup.updateTime
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_linkedin_sys_taskgroup.updateTime
	 * 
	 * @param updatetime
	 *            the value for tb_linkedin_sys_taskgroup.updateTime
	 * @mbg.generated Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}