package com.shty.collect.domain;

import java.util.Date;

public class TbSystemLinkaccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.userName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.ipAddress
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String ipaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.sharedKey
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String sharedkey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.vpnType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String vpntype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Byte isused;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_linkaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.id
	 * @return  the value of tb_system_linkaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.id
	 * @param id  the value for tb_system_linkaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.userName
	 * @return  the value of tb_system_linkaccount.userName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.userName
	 * @param username  the value for tb_system_linkaccount.userName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.password
	 * @return  the value of tb_system_linkaccount.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.password
	 * @param password  the value for tb_system_linkaccount.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.ipAddress
	 * @return  the value of tb_system_linkaccount.ipAddress
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getIpaddress() {
		return ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.ipAddress
	 * @param ipaddress  the value for tb_system_linkaccount.ipAddress
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.sharedKey
	 * @return  the value of tb_system_linkaccount.sharedKey
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getSharedkey() {
		return sharedkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.sharedKey
	 * @param sharedkey  the value for tb_system_linkaccount.sharedKey
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setSharedkey(String sharedkey) {
		this.sharedkey = sharedkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.vpnType
	 * @return  the value of tb_system_linkaccount.vpnType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getVpntype() {
		return vpntype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.vpnType
	 * @param vpntype  the value for tb_system_linkaccount.vpnType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setVpntype(String vpntype) {
		this.vpntype = vpntype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.isused
	 * @return  the value of tb_system_linkaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Byte getIsused() {
		return isused;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.isused
	 * @param isused  the value for tb_system_linkaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setIsused(Byte isused) {
		this.isused = isused;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.creatTime
	 * @return  the value of tb_system_linkaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.creatTime
	 * @param creattime  the value for tb_system_linkaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_linkaccount.updateTime
	 * @return  the value of tb_system_linkaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_linkaccount.updateTime
	 * @param updatetime  the value for tb_system_linkaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}