package com.shty.collect.domain;

import java.util.Date;

public class TbSystemUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.user
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.authority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Integer authority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_user.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.id
	 * @return  the value of tb_system_user.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.id
	 * @param id  the value for tb_system_user.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.user
	 * @return  the value of tb_system_user.user
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.user
	 * @param user  the value for tb_system_user.user
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.password
	 * @return  the value of tb_system_user.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.password
	 * @param password  the value for tb_system_user.password
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.authority
	 * @return  the value of tb_system_user.authority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Integer getAuthority() {
		return authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.authority
	 * @param authority  the value for tb_system_user.authority
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setAuthority(Integer authority) {
		this.authority = authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.creatTime
	 * @return  the value of tb_system_user.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.creatTime
	 * @param creattime  the value for tb_system_user.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_user.updateTime
	 * @return  the value of tb_system_user.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_user.updateTime
	 * @param updatetime  the value for tb_system_user.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}