package com.shty.collect.domain;

import java.util.Date;

public class TbSystemSociallimit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_sociallimit.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_sociallimit.sleepTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String sleeptime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_sociallimit.limitNumber
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Integer limitnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_sociallimit.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_sociallimit.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_sociallimit.id
	 * @return  the value of tb_system_sociallimit.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_sociallimit.id
	 * @param id  the value for tb_system_sociallimit.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_sociallimit.sleepTime
	 * @return  the value of tb_system_sociallimit.sleepTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getSleeptime() {
		return sleeptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_sociallimit.sleepTime
	 * @param sleeptime  the value for tb_system_sociallimit.sleepTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setSleeptime(String sleeptime) {
		this.sleeptime = sleeptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_sociallimit.limitNumber
	 * @return  the value of tb_system_sociallimit.limitNumber
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Integer getLimitnumber() {
		return limitnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_sociallimit.limitNumber
	 * @param limitnumber  the value for tb_system_sociallimit.limitNumber
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setLimitnumber(Integer limitnumber) {
		this.limitnumber = limitnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_sociallimit.creatTime
	 * @return  the value of tb_system_sociallimit.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_sociallimit.creatTime
	 * @param creattime  the value for tb_system_sociallimit.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_sociallimit.updateTime
	 * @return  the value of tb_system_sociallimit.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_sociallimit.updateTime
	 * @param updatetime  the value for tb_system_sociallimit.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}