package com.shty.collect.domain;

import java.util.Date;

public class TbSystemRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.nodeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long nodeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.linkId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long linkid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.socialId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long socialid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_relation.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.id
	 * @return  the value of tb_system_relation.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.id
	 * @param id  the value for tb_system_relation.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.nodeId
	 * @return  the value of tb_system_relation.nodeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getNodeid() {
		return nodeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.nodeId
	 * @param nodeid  the value for tb_system_relation.nodeId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setNodeid(Long nodeid) {
		this.nodeid = nodeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.linkId
	 * @return  the value of tb_system_relation.linkId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getLinkid() {
		return linkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.linkId
	 * @param linkid  the value for tb_system_relation.linkId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setLinkid(Long linkid) {
		this.linkid = linkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.socialId
	 * @return  the value of tb_system_relation.socialId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getSocialid() {
		return socialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.socialId
	 * @param socialid  the value for tb_system_relation.socialId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setSocialid(Long socialid) {
		this.socialid = socialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.creatTime
	 * @return  the value of tb_system_relation.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.creatTime
	 * @param creattime  the value for tb_system_relation.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_relation.updateTime
	 * @return  the value of tb_system_relation.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_relation.updateTime
	 * @param updatetime  the value for tb_system_relation.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}