package com.shty.collect.domain;

public class TbSysThirdTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.id
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.updatetime
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.creattime
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.tasktype
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String tasktype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.url
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.personid
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String personid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.keyword
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.taskstatus
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String taskstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_sys_third_task.userId
	 * 
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	private String userid;

	private int profileid;

	private String fullname;

	public int getProfileid() {
		return profileid;
	}

	public void setProfileid(int profileid) {
		this.profileid = profileid;
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.id
	 * 
	 * @return the value of tb_sys_third_task.id
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.id
	 * 
	 * @param id
	 *            the value for tb_sys_third_task.id
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.updatetime
	 * 
	 * @return the value of tb_sys_third_task.updatetime
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.updatetime
	 * 
	 * @param updatetime
	 *            the value for tb_sys_third_task.updatetime
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.creattime
	 * 
	 * @return the value of tb_sys_third_task.creattime
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.creattime
	 * 
	 * @param creattime
	 *            the value for tb_sys_third_task.creattime
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setCreattime(String creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.tasktype
	 * 
	 * @return the value of tb_sys_third_task.tasktype
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getTasktype() {
		return tasktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.tasktype
	 * 
	 * @param tasktype
	 *            the value for tb_sys_third_task.tasktype
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setTasktype(String tasktype) {
		this.tasktype = tasktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.url
	 * 
	 * @return the value of tb_sys_third_task.url
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.url
	 * 
	 * @param url
	 *            the value for tb_sys_third_task.url
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.personid
	 * 
	 * @return the value of tb_sys_third_task.personid
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getPersonid() {
		return personid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.personid
	 * 
	 * @param personid
	 *            the value for tb_sys_third_task.personid
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setPersonid(String personid) {
		this.personid = personid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.keyword
	 * 
	 * @return the value of tb_sys_third_task.keyword
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.keyword
	 * 
	 * @param keyword
	 *            the value for tb_sys_third_task.keyword
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.taskstatus
	 * 
	 * @return the value of tb_sys_third_task.taskstatus
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getTaskstatus() {
		return taskstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.taskstatus
	 * 
	 * @param taskstatus
	 *            the value for tb_sys_third_task.taskstatus
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setTaskstatus(String taskstatus) {
		this.taskstatus = taskstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_sys_third_task.userId
	 * 
	 * @return the value of tb_sys_third_task.userId
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_sys_third_task.userId
	 * 
	 * @param userid
	 *            the value for tb_sys_third_task.userId
	 * @mbg.generated Mon Sep 04 09:18:24 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}
}