package com.shty.collect.domain;

import java.util.Date;

public class TbSystemSocialaccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.accountName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String accountname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.passowrd
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.accountType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String accounttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String isused;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.limitTableId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long limittableid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long httpid;
	public Long getHttpid() {
		return httpid;
	}

	public void setHttpid(Long httpid) {
		this.httpid = httpid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String creattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_socialaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.id
	 * @return  the value of tb_system_socialaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.id
	 * @param id  the value for tb_system_socialaccount.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.accountName
	 * @return  the value of tb_system_socialaccount.accountName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getAccountname() {
		return accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.accountName
	 * @param accountname  the value for tb_system_socialaccount.accountName
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.passowrd
	 * @return  the value of tb_system_socialaccount.passowrd
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.passowrd
	 * @param passowrd  the value for tb_system_socialaccount.passowrd
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.accountType
	 * @return  the value of tb_system_socialaccount.accountType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getAccounttype() {
		return accounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.accountType
	 * @param accounttype  the value for tb_system_socialaccount.accountType
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setAccounttype(String accounttype) {
		this.accounttype = accounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.isused
	 * @return  the value of tb_system_socialaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getIsused() {
		return isused;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.isused
	 * @param isused  the value for tb_system_socialaccount.isused
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setIsused(String isused) {
		this.isused = isused;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.limitTableId
	 * @return  the value of tb_system_socialaccount.limitTableId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getLimittableid() {
		return limittableid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.limitTableId
	 * @param limittableid  the value for tb_system_socialaccount.limitTableId
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setLimittableid(Long limittableid) {
		this.limittableid = limittableid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.creatTime
	 * @return  the value of tb_system_socialaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.creatTime
	 * @param creattime  the value for tb_system_socialaccount.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(String creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_socialaccount.updateTime
	 * @return  the value of tb_system_socialaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_socialaccount.updateTime
	 * @param updatetime  the value for tb_system_socialaccount.updateTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}
}