package com.shty.collect.domain;

import java.util.Date;

public class TbSystemRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_record.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_record.operator
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_record.action
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_system_record.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	private Date creattime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_record.id
	 * @return  the value of tb_system_record.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_record.id
	 * @param id  the value for tb_system_record.id
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_record.operator
	 * @return  the value of tb_system_record.operator
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_record.operator
	 * @param operator  the value for tb_system_record.operator
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_record.action
	 * @return  the value of tb_system_record.action
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_record.action
	 * @param action  the value for tb_system_record.action
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_system_record.creatTime
	 * @return  the value of tb_system_record.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_system_record.creatTime
	 * @param creattime  the value for tb_system_record.creatTime
	 * @mbg.generated  Wed Jun 07 10:53:40 CST 2017
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}
}